### PR TITLE
Proxy websocket connections to the bare domain

### LINKED ISSUE #5: socket.io proxying breaks when proxying to a non-root path
If you proxy to:

```
http://example.com/api
```

socket.io proxying does not work. It will try to proxy to:

```
http://example.com/api/socket.io/
```

When it should be:

```
http://example.com/socket.io/
```

Question @daffl, is socket.io always served at `/socket.io/`?   If so we could just fix the socket.io case directly. Otherwise we might have to add another option `--websocket-proxy` or something like that.

### PR DESCRIPTION
**Pull request by matthewp**
This does two things:
1. Ensures that the websocket proxying goes to the bare domain.
2. Ensure that the socket.io http proxy goes to the bare domain +
   '/socket.io/'

I'm making the assumption that this is correct. Closes #5

### CODE REVIEW

**Comment by matthewp** [comment]
@daffl your review of this would be appreciated.

**Comment by daffl** [comment]
Looks great, thank you for getting that in!

File: lib/proxy.js [hunk 1]
```diff
@@ -19,18 +20,25 @@ module.exports = function (app, options) {
 	}
 
 	app.use(apiPath, middleware(options.proxy));
-	app.use('/socket.io/', middleware(options.proxy + '/socket.io/'));
+
+	app.use('/socket.io/', middleware(baseDomain(options.proxy) + 'socket.io/'));
```
Comment (daffl) [inline lib/proxy.js:24]: The `/socket.io` should be configurable since you can change it when setting up Socket.io

**Comment by daffl** [comment]
Actually, one comment, then :shipit:

File: lib/proxy.js (hunk 1 above)
Comment (matthewp) [inline lib/proxy.js:24]: what would that look like, something like `--socketio-root` or something?

Comment (daffl) [inline lib/proxy.js:24]: Yes. Or `--socketio-path`

**Comment by matthewp** [comment]
Going to do that in a new issue, want to get this released since it's breaking PMO.  https://github.com/donejs/done-serve/issues/7

**Comment by daffl** [comment]
Yep, good call, not a super urgent issue.
